"""
Django settings for pms_api project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
import dj_database_url

# ─────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (local dev). On Vercel, env vars come from Project Settings.
load_dotenv(BASE_DIR / '.env')


# ─────────────────────────────────────────────
# Core security
# ─────────────────────────────────────────────
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-*p@p6w2myy(x^+!_-u_4i**y!&gc*(0g&#!^%18c(2pu)wssbl'
)

# In prod (Vercel), DEBUG must be False. Locally defaults to True.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Vercel gives you a URL like <project>.vercel.app — allow it plus all.
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS', '*'
).split(',')


# ─────────────────────────────────────────────
# Applications
# ─────────────────────────────────────────────
AUTH_USER_MODEL = 'pms_app.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'pms_app',
    'corsheaders',
]


# ─────────────────────────────────────────────
# Middleware
# ─────────────────────────────────────────────
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',          # must be high
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ─────────────────────────────────────────────
# DRF
# ─────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


# ─────────────────────────────────────────────
# JWT
# ─────────────────────────────────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}


# ─────────────────────────────────────────────
# Email — Gmail SMTP (via App Password)
# ─────────────────────────────────────────────
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # safe fallback for dev
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'AEEL-PMS <noreply@aeel-pms.local>'
)

# Frontend URL — used to build verification links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# 24-hour expiry for email verification tokens
PASSWORD_RESET_TIMEOUT = 86400


# ─────────────────────────────────────────────
# CORS — frontend origins allowed to call this API
# ─────────────────────────────────────────────
# Comma-separated in env var (no spaces). Includes localhost + Vercel frontend.
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://localhost:3000,'
        'https://pms-frontend.vercel.app,'
        'https://aeel-pms.vercel.app'
    ).split(',') if o.strip()
]

# Only for dev — remove this in prod once you know the exact origins.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# ─────────────────────────────────────────────
# CSRF — required because Vercel proxies with HTTPS
# ─────────────────────────────────────────────
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://localhost:3000,'
        'https://pms-backend-fawn-pi.vercel.app,'
        'https://pms-frontend.vercel.app,'
        'https://aeel-pms.vercel.app'
    ).split(',') if o.strip()
]

# Vercel serves over HTTPS but forwards HTTP internally — this tells Django
# to trust the X-Forwarded-Proto header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Only require HTTPS redirects in prod (breaks local dev otherwise)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ─────────────────────────────────────────────
# URLs / Templates
# ─────────────────────────────────────────────
ROOT_URLCONF = 'pms_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pms_api.wsgi.application'


# ─────────────────────────────────────────────
# Database — Neon PostgreSQL (prod) / SQLite (dev)
# ─────────────────────────────────────────────
# If DATABASE_URL is set (e.g. Neon), use it. Otherwise fall back to SQLite
# so local dev still works without any setup.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# ─────────────────────────────────────────────
# Password validation
# ─────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─────────────────────────────────────────────
# i18n
# ─────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ─────────────────────────────────────────────
# Static files
# ─────────────────────────────────────────────
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Only add STATICFILES_DIRS if the folder actually exists — otherwise
# Django throws a warning/error during collectstatic on Vercel.
_static_dir = BASE_DIR / 'static'
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []


# ─────────────────────────────────────────────
# Misc
# ─────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'