# Generated by Django 6.0.4 on 2026-08-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0005_comment_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTeam',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('p', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='p_teams', to='pms_app.project')),
                ('t', models.ForeignKey(blank=True, db_column='t_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_teams', to='pms_app.task')),
                ('tm', models.ForeignKey(blank=True, db_column='tm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_teams', to='pms_app.teammember')),
            ],
            options={
                'verbose_name': 'Project Team Entry',
                'db_table': 'p_team',
            },
        ),
    ]
