# Generated by Django 6.0.4 on 2026-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0009_preserve_existing_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percent complete, 0-100'),
        ),
    ]
