# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0011_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(
                blank=True,
                related_name='multi_assigned_tasks',
                to='pms_app.teammember',
            ),
        ),
    ]